import '../../styles/globals.css';
export const metadata = {
    title:"Create Next App",
    description : "Generated by next app",
}

/*This function takes all the components that need to be present on all pages, e.g footer and navbar*/
/* children prop renders the page */
const RootLayout = ({children}) => {
    return(
        <html lang='en'>
            <div className="App">
                <header className="App-header">
                    {children}
                </header>
                
            </div>
            
        </html>
    )
}
export default RootLayout